service: hyperion-assembly-backend

frameworkVersion: "3"
plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: config.wsgi_handler.py
    packRequirements: false
  pythonRequirements:
    zip: true
    slim: true

provider:
  name: aws
  runtime: python3.11
  environment:
    GITHUB_WEBHOOK_SECRET: ${param:GITHUB_WEBHOOK_SECRET}
    DJANGO_SECRET_KEY: ${param:DJANGO_SECRET_KEY}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - s3:GetObject
            - s3:PutObject
          Resource: "arn:aws:s3:::*"

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"
